### PR TITLE
MM-40214: Add App Bar icon

### PR DESCRIPTION
**Pull request by agarciamontoro**
#### Summary
This PR adds a new icon explicitly for the App Bar, so that when it is enabled, the proper icon is shown. The logic for rendering the channel header icon or the App Bar one is in the webapp, not here.

image

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40214

### CODE REVIEW

**Comment by agarciamontoro** [comment]
This PR is not needed before code freeze (today), but we're aiming to release a new version of the plugin with this PR before the release of v7.0 on June 15 (one week from today).

**Comment by agarciamontoro** [comment]
@mickmister, haha, I was just doing that, thank you!

**Comment by agarciamontoro** [comment]
Swapping Daniel with Lev because Daniel's out

**Comment by agarciamontoro** [comment]
@lindalumitchell, the build plugin is in the *second* artifact linked here: https://app.circleci.com/pipelines/github/mattermost/mattermost-plugin-skype4business/732/workflows/e0ff5e50-cc7b-4c60-9923-b3b9d72af4b0/jobs/2228/artifacts

**Review by lindalumitchell — APPROVED** [review]
Tested on postgres.test (v7.0.0-rc4) and looks great. Chatted with Dylan about some issues around testing on cloud test servers at the moment, and we agree that approval is okay with this testing on postgres.test. LGTM!

**Pull request merged**
